# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbcd83d0371eb5e2e77f4c95754266c942cfef8a375ca5a89b9928aafcdc31cfe7a590711130366e7410d87e0fab0a9a5018e1c17fe1009451024f590343749d

test:
  secret_key_base: 3a23502672cf1a95c585befbc396717412399d4fb04f0b720dbe11a783b055140200887bb55ecebf258598ee40d0cccc32779e6b4dc450b67a56108d7be4a878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
